### PR TITLE
Update example to use NXmpes_arpes

### PR DESCRIPTION
**Pull request by domna**
This updates the example to use NXmpes_arpes and makes the appropriate fixes in the config file to align with the new pynxtools validation.

### CODE REVIEW

**Comment by rettigl** [comment]
@domna I think there is no release of pynxtools yet, that contains definitions with NXmpes_arpes. Can you make one, and mybe also update the requirements of pynxtools_mpes accordingly?

**Comment by domna** [comment]
> @domna I think there is no release of pynxtools yet, that contains definitions with NXmpes_arpes. Can you make one, and mybe also update the requirements of pynxtools_mpes accordingly?

Yes, I will as soon as this https://github.com/FAIRmat-NFDI/pynxtools/pull/339 is merged. This PR is also the prerequesite for these changes here.

**Comment by rettigl** [comment]
With https://github.com/FAIRmat-NFDI/pynxtools/pull/339https://github.com/FAIRmat-NFDI/pynxtools/pull/339 this appears to work, also with the yaml-based metadata.
The only thing I am wondering: Why is it required to remove the UPPERCASE concept notation for elements that are part of the application definition? Should the uppercase notation not also refer to the same concept? There cannot be another element with the same name as the one in the appdef, so I would argue that both should work. Or is there a use-case where you want to distinct between an element in the appdef, and one from the base class concept, that have the same name?
I.e.:
`ENTRY[entry]/DATA[data]` and `ENTRY[entry]/data` should resolve to the same concept.
Obvoiously e.g. `ENTRY[entry]/DATA[data2]` would be something different.

**Comment by domna** [comment]
> With [FAIRmat-NFDI/pynxtools#339](https://github.com/FAIRmat-NFDI/pynxtools/pull/339) this appears to work, also with the yaml-based metadata. The only thing I am wondering: Why is it required to remove the UPPERCASE concept notation for elements that are part of the application definition? Should the uppercase notation not also refer to the same concept? There cannot be another element with the same name as the one in the appdef, so I would argue that both should work. Or is there a use-case where you want to distinct between an element in the appdef, and one from the base class concept, that have the same name? I.e.: `ENTRY[entry]/DATA[data]` and `ENTRY[entry]/data` should resolve to the same concept. Obvoiously e.g. `ENTRY[entry]/DATA[data2]` would be something different.

I agree and I already included the behaviour in https://github.com/FAIRmat-NFDI/pynxtools/pull/339. If there are still problems with it I might need to check again as I just did this based on one config.

**Review by rettigl — APPROVED** [review]
Once you've merged the other branches, please update the requirements on pynxtools, and then merge.

**Comment by rettigl** [comment]
One more thing: I tried to run the conversion through on the upload in the central nomad. This works fine, but the resulting file cannot be parsed propperly. Maybe the necessary definition files are not part of this configuration?

**Comment by rettigl** [comment]
> It will not work for fields and attributes, though. We have to rely on namefitting there as I explained in the above PR already (in [this](https://github.com/FAIRmat-NFDI/pynxtools/pull/339#issuecomment-2154393819) comment right at the bottom).

Also for NXmpes this does not make any differences now, and I agree that we conceptually cannot easily tell which type of field this should be. I think I had to add these uppercase notations earlier, but this is apparently different now in the new verification routine.

**Comment by rettigl** [comment]
@domna I am merging this now with the new versions of pynxtools and pynxtools-mpes. Any additional changes, e.g. https://github.com/FAIRmat-NFDI/nexus_definitions/pull/205 can be addressed in a different PR.

**Pull request merged**
